import * as React from "react";
import{useState,useEffect,useRef,useCallback,useMemo}from"react";
import MatchIntelPanel from"./MatchIntelPanel.jsx";

const LOGOS={IPL:"https://documents.iplt20.com/ipl/assets/images/ipl-logo-new-old.png",RCB:"https://documents.iplt20.com/ipl/RCB/Logos/Logooutline/RCBoutline.png",SRH:"https://documents.iplt20.com/ipl/SRH/Logos/Logooutline/SRHoutline.png",MI:"https://documents.iplt20.com/ipl/MI/Logos/Logooutline/MIoutline.png",KKR:"https://documents.iplt20.com/ipl/KKR/Logos/Logooutline/KKRoutline.png",CSK:"https://documents.iplt20.com/ipl/CSK/logos/Logooutline/CSKoutline.png",RR:"https://documents.iplt20.com/ipl/RR/Logos/Logooutline/RRoutline.png",PBKS:"https://documents.iplt20.com/ipl/PBKS/Logos/Logooutline/PBKSoutline.png",GT:"https://documents.iplt20.com/ipl/GT/Logos/Logooutline/GToutline.png",LSG:"https://documents.iplt20.com/ipl/LSG/Logos/Logooutline/LSGoutline.png",DC:"https://documents.iplt20.com/ipl/DC/Logos/LogoOutline/DCoutline.png"};
const TC={RCB:{bg:"#C8102E",dk:"#FFD700"},SRH:{bg:"#FF822A",dk:"#1B1B1B"},MI:{bg:"#004BA0",dk:"#fff"},KKR:{bg:"#3A225D",dk:"#FFD700"},CSK:{bg:"#F5C600",dk:"#003566"},RR:{bg:"#2D0A6B",dk:"#E91E8C"},PBKS:{bg:"#ED1B24",dk:"#fff"},GT:{bg:"#1B3A6B",dk:"#B5985A"},LSG:{bg:"#A72056",dk:"#fff"},DC:{bg:"#00008B",dk:"#fff"}};
const TF={RCB:"Royal Challengers Bengaluru",SRH:"Sunrisers Hyderabad",MI:"Mumbai Indians",KKR:"Kolkata Knight Riders",CSK:"Chennai Super Kings",RR:"Rajasthan Royals",PBKS:"Punjab Kings",GT:"Gujarat Titans",LSG:"Lucknow Super Giants",DC:"Delhi Capitals"};
const TEAMS=Object.keys(TF);
const SQ={
  RCB:["Virat Kohli","Rajat Patidar","Phil Salt","Devdutt Padikkal","Jitesh Sharma","Tim David","Krunal Pandya","Swapnil Singh","Jacob Bethell","Romario Shepherd","Nuwan Thushara","Josh Hazlewood","Bhuvneshwar Kumar","Yash Dayal","Rasikh Dar","Suyash Sharma","Abhinandan Singh","Liam Livingstone","Jacob Duffy","Mohit Rathee","Lungi Ngidi"],
  SRH:["Travis Head","Abhishek Sharma","Ishan Kishan","Heinrich Klaasen","Nitish Kumar Reddy","Pat Cummins","Harshal Patel","Brydon Carse","Liam Livingstone","Jaydev Unadkat","Shivam Mavi","Kamindu Mendis","Aniket Verma","Harsh Dubey","Eshan Malinga","Salil Arora","Smaran Ravichandran","Amit Kumar","Jack Edwards","Zeeshan Ansari","Praful Hinge","Onkar Tarmale","Sakib Hussain","Shivang Kumar","Krains Fuletra"],
  MI:["Rohit Sharma","Suryakumar Yadav","Hardik Pandya","Jasprit Bumrah","Tilak Varma","Ryan Rickelton","Naman Dhir","Robin Minz","Will Jacks","Mitchell Santner","Raj Angad Bawa","Trent Boult","Deepak Chahar","Shardul Thakur","AM Ghazanfar","Corbin Bosch","Ashwani Kumar","Raghu Sharma","Sherfane Rutherford","Mayank Markande","Bevon Jacobs"],
  KKR:["Ajinkya Rahane","Angkrish Raghuvanshi","Rinku Singh","Venkatesh Iyer","Cameron Green","Sunil Narine","Varun Chakaravarthy","Harshit Rana","Vaibhav Arora","Matheesha Pathirana","Blessing Muzarabani","Ramandeep Singh","Anukul Roy","Tim Seifert","Finn Allen","Rachin Ravindra","Rahul Tripathi","Kartik Tyagi","Saurabh Dubey","Manish Pandey","Luvnith Sisodia"],
  CSK:["Ruturaj Gaikwad","Sanju Samson","Ayush Mhatre","Shivam Dube","Dewald Brevis","MS Dhoni","Urvil Patel","Noor Ahmad","Nathan Ellis","Khaleel Ahmed","Anshul Kamboj","Gurjapneet Singh","Mukesh Choudhary","Jamie Overton","Ramakrishna Ghosh","Shreyas Gopal","Prashant Veer","Kartik Sharma","Akeal Hosein","Matt Henry","Matthew Short","Sarfaraz Khan","Zak Foulkes","Rahul Chahar","Aman Khan"],
  RR:["Yashasvi Jaiswal","Vaibhav Suryavanshi","Riyan Parag","Shimron Hetmyer","Dhruv Jurel","Ravindra Jadeja","Sam Curran","Donovan Ferreira","Jofra Archer","Nandre Burger","Sandeep Sharma","Tushar Deshpande","Ravi Bishnoi","Shubham Dubey","Yudhvir Singh Charak","Kwena Maphaka","Lhuan-dre Pretorius","Adam Milne","Ravi Singh","Sushant Mishra","Kuldeep Sen","Vignesh Puthur","Yash Raj Punja","Aman Rao","Brijesh Sharma"],
  PBKS:["Shreyas Iyer","Prabhsimran Singh","Priyansh Arya","Shashank Singh","Nehal Wadhera","Marcus Stoinis","Azmatullah Omarzai","Marco Jansen","Arshdeep Singh","Yuzvendra Chahal","Lockie Ferguson","Xavier Bartlett","Musheer Khan","Harpreet Brar","Cooper Connolly","Ben Dwarshuis","Pravin Dubey","Vishal Nishad","Harnoor Pannu","Pyla Avinash","Suryansh Shedge"],
  GT:["Shubman Gill","Jos Buttler","Sai Sudharsan","Shahrukh Khan","Washington Sundar","Rahul Tewatia","Rashid Khan","Kagiso Rabada","Mohammed Siraj","Prasidh Krishna","Gerald Coetzee","Jayant Yadav","Nishant Sindhu","Manav Suthar","Kulwant Khejroliya","Gurnoor Brar","Sai Kishore","Anuj Rawat","Arshad Khan","Matthew Wade","Karim Janat"],
  LSG:["Rishabh Pant","Mitchell Marsh","Nicholas Pooran","Aiden Markram","Abdul Samad","Ayush Badoni","Himmat Singh","Shahbaz Ahmed","Digvesh Rathi","Mohammed Shami","Avesh Khan","Mayank Yadav","Anrich Nortje","Wanindu Hasaranga","Akash Singh","Matthew Breetzke","Arshin Kulkarni","Manimaran Siddharth","Josh Inglis","Mukul Choudhary","Akshat Raghuwanshi","Naman Tiwari","Mohsin Khan","Prince Yadav","Arjun Tendulkar"],
  DC:["KL Rahul","Axar Patel","Abishek Porel","Ashutosh Sharma","Karun Nair","Kuldeep Yadav","Mitchell Starc","T. Natarajan","Dushmantha Chameera","Jake Fraser-McGurk","Tristan Stubbs","Sameer Rizvi","Ajay Mandal","Madhav Tiwari","Vipraj Nigam","Nitish Rana","Faf du Plessis","Mukesh Kumar","Tripurana Vijay","Darshan Nalkande","Donovan Ferreira"]
};