// src/data/players.js
// IPL 2026 — Verified rosters from iplt20.com / official sources
// Roles: BAT | BOWL | AR | WK
// credit: approximate Dream11-style credit value

export const PLAYERS = {

  // ─── CSK — Chennai Super Kings ────────────────────────────────────────
  "ruturaj-gaikwad":      { name: "Ruturaj Gaikwad",      team: "CSK", role: "BAT",  credit: 9.5 },
  "ms-dhoni":             { name: "MS Dhoni",              team: "CSK", role: "WK",   credit: 9.5 },
  "sanju-samson":         { name: "Sanju Samson",          team: "CSK", role: "WK",   credit: 9.5 },
  "dewald-brevis":        { name: "Dewald Brevis",         team: "CSK", role: "BAT",  credit: 8.5 },
  "ayush-mhatre":         { name: "Ayush Mhatre",          team: "CSK", role: "BAT",  credit: 7.5 },
  "kartik-sharma-csk":    { name: "Kartik Sharma",         team: "CSK", role: "BAT",  credit: 8.0 },
  "sarfaraz-khan":        { name: "Sarfaraz Khan",         team: "CSK", role: "BAT",  credit: 8.0 },
  "urvil-patel":          { name: "Urvil Patel",           team: "CSK", role: "WK",   credit: 7.0 },
  "jamie-overton":        { name: "Jamie Overton",         team: "CSK", role: "AR",   credit: 8.0 },
  "ramakrishna-ghosh":    { name: "Ramakrishna Ghosh",     team: "CSK", role: "AR",   credit: 7.0 },
  "prashant-veer":        { name: "Prashant Veer",         team: "CSK", role: "AR",   credit: 8.0 },
  "matthew-short":        { name: "Matthew Short",         team: "CSK", role: "AR",   credit: 8.0 },
  "aman-khan":            { name: "Aman Khan",             team: "CSK", role: "AR",   credit: 7.0 },
  "zak-foulkes":          { name: "Zak Foulkes",           team: "CSK", role: "AR",   credit: 7.0 },
  "shivam-dube":          { name: "Shivam Dube",           team: "CSK", role: "AR",   credit: 9.0 },
  "khaleel-ahmed-csk":    { name: "Khaleel Ahmed",         team: "CSK", role: "BOWL", credit: 8.0 },
  "noor-ahmad":           { name: "Noor Ahmad",            team: "CSK", role: "BOWL", credit: 8.5 },
  "anshul-kamboj":        { name: "Anshul Kamboj",         team: "CSK", role: "BOWL", credit: 7.5 },
  "mukesh-choudhary":     { name: "Mukesh Choudhary",      team: "CSK", role: "BOWL", credit: 7.5 },
  "shreyas-gopal":        { name: "Shreyas Gopal",         team: "CSK", role: "BOWL", credit: 7.5 },
  "gurjapneet-singh":     { name: "Gurjapneet Singh",      team: "CSK", role: "BOWL", credit: 7.0 },
  "akeal-hosein":         { name: "Akeal Hosein",          team: "CSK", role: "BOWL", credit: 7.5 },
  "matt-henry":           { name: "Matt Henry",            team: "CSK", role: "BOWL", credit: 8.0 },
  "rahul-chahar":         { name: "Rahul Chahar",          team: "CSK", role: "BOWL", credit: 8.0 },
  "spencer-johnson":      { name: "Spencer Johnson",       team: "CSK", role: "BOWL", credit: 8.0 },

  // ─── DC — Delhi Capitals ─────────────────────────────────────────────
  "kl-rahul":             { name: "KL Rahul",              team: "DC",  role: "WK",   credit: 10.0 },
  "karun-nair":           { name: "Karun Nair",            team: "DC",  role: "BAT",  credit: 8.0 },
  "david-miller":         { name: "David Miller",          team: "DC",  role: "BAT",  credit: 9.0 },
  "pathum-nissanka":      { name: "Pathum Nissanka",       team: "DC",  role: "BAT",  credit: 8.5 },
  "sahil-parakh":         { name: "Sahil Parakh",          team: "DC",  role: "BAT",  credit: 7.0 },
  "prithvi-shaw":         { name: "Prithvi Shaw",          team: "DC",  role: "BAT",  credit: 8.5 },
  "abhishek-porel":       { name: "Abhishek Porel",        team: "DC",  role: "WK",   credit: 8.0 },
  "tristan-stubbs":       { name: "Tristan Stubbs",        team: "DC",  role: "BAT",  credit: 8.5 },
  "axar-patel":           { name: "Axar Patel",            team: "DC",  role: "AR",   credit: 10.0 },
  "sameer-rizvi":         { name: "Sameer Rizvi",          team: "DC",  role: "AR",   credit: 7.5 },
  "ashutosh-sharma":      { name: "Ashutosh Sharma",       team: "DC",  role: "AR",   credit: 7.5 },
  "vipraj-nigam":         { name: "Vipraj Nigam",          team: "DC",  role: "AR",   credit: 7.0 },
  "ajay-mandal":          { name: "Ajay Mandal",           team: "DC",  role: "AR",   credit: 7.0 },
  "nitish-rana":          { name: "Nitish Rana",           team: "DC",  role: "AR",   credit: 8.5 },
  "mitchell-starc":       { name: "Mitchell Starc",        team: "DC",  role: "BOWL", credit: 9.5 },
  "t-natarajan":          { name: "T. Natarajan",          team: "DC",  role: "BOWL", credit: 8.5 },
  "mukesh-kumar":         { name: "Mukesh Kumar",          team: "DC",  role: "BOWL", credit: 8.0 },
  "dushmantha-chameera":  { name: "Dushmantha Chameera",   team: "DC",  role: "BOWL", credit: 8.0 },
  "auqib-nabi":           { name: "Auqib Nabi",            team: "DC",  role: "BOWL", credit: 7.0 },
  "lungisani-ngidi":      { name: "Lungisani Ngidi",       team: "DC",  role: "BOWL", credit: 8.0 },
  "kyle-jamieson":        { name: "Kyle Jamieson",         team: "DC",  role: "AR",   credit: 8.5 },
  "kuldeep-yadav":        { name: "Kuldeep Yadav",         team: "DC",  role: "BOWL", credit: 9.0 },

  // ─── GT — Gujarat Titans ─────────────────────────────────────────────
  "shubman-gill":         { name: "Shubman Gill",          team: "GT",  role: "BAT",  credit: 10.0 },
  "jos-buttler":          { name: "Jos Buttler",           team: "GT",  role: "WK",   credit: 10.0 },
  "kumar-kushagra":       { name: "Kumar Kushagra",        team: "GT",  role: "WK",   credit: 7.5 },
  "anuj-rawat":           { name: "Anuj Rawat",            team: "GT",  role: "WK",   credit: 7.5 },
  "tom-banton":           { name: "Tom Banton",            team: "GT",  role: "WK",   credit: 7.5 },
  "glenn-phillips":       { name: "Glenn Phillips",        team: "GT",  role: "AR",   credit: 9.0 },
  "sai-sudharsan":        { name: "Sai Sudharsan",         team: "GT",  role: "BAT",  credit: 9.0 },
  "nishant-sindhu":       { name: "Nishant Sindhu",        team: "GT",  role: "AR",   credit: 7.5 },
  "washington-sundar":    { name: "Washington Sundar",     team: "GT",  role: "AR",   credit: 9.0 },
  "sai-kishore":          { name: "Sai Kishore",           team: "GT",  role: "BOWL", credit: 8.0 },
  "jayant-yadav":         { name: "Jayant Yadav",          team: "GT",  role: "AR",   credit: 8.0 },
  "jason-holder":         { name: "Jason Holder",          team: "GT",  role: "AR",   credit: 8.5 },
  "rahul-tewatia":        { name: "Rahul Tewatia",         team: "GT",  role: "AR",   credit: 8.5 },
  "shahrukh-khan-gt":     { name: "Shahrukh Khan",         team: "GT",  role: "BAT",  credit: 8.0 },
  "kagiso-rabada":        { name: "Kagiso Rabada",         team: "GT",  role: "BOWL", credit: 9.5 },
  "mohammed-siraj":       { name: "Mohammed Siraj",        team: "GT",  role: "BOWL", credit: 9.0 },
  "prasidh-krishna":      { name: "Prasidh Krishna",       team: "GT",  role: "BOWL", credit: 8.5 },
  "manav-suthar":         { name: "Manav Suthar",          team: "GT",  role: "BOWL", credit: 7.5 },
  "gurnoor-brar":         { name: "Gurnoor Singh Brar",    team: "GT",  role: "BOWL", credit: 7.5 },
  "ishant-sharma":        { name: "Ishant Sharma",         team: "GT",  role: "BOWL", credit: 8.0 },
  "rashid-khan":          { name: "Rashid Khan",           team: "GT",  role: "BOWL", credit: 10.0 },

  // ─── KKR — Kolkata Knight Riders ─────────────────────────────────────
  "ajinkya-rahane":       { name: "Ajinkya Rahane",        team: "KKR", role: "BAT",  credit: 8.5 },
  "rinku-singh":          { name: "Rinku Singh",           team: "KKR", role: "BAT",  credit: 9.0 },
  "angkrish-raghuvanshi": { name: "Angkrish Raghuvanshi",  team: "KKR", role: "BAT",  credit: 7.5 },
  "manish-pandey":        { name: "Manish Pandey",         team: "KKR", role: "BAT",  credit: 8.0 },
  "finn-allen":           { name: "Finn Allen",            team: "KKR", role: "WK",   credit: 8.5 },
  "rahul-tripathi":       { name: "Rahul Tripathi",        team: "KKR", role: "BAT",  credit: 8.0 },
  "tim-seifert":          { name: "Tim Seifert",           team: "KKR", role: "WK",   credit: 7.5 },
  "rovman-powell":        { name: "Rovman Powell",         team: "KKR", role: "BAT",  credit: 8.5 },
  "cameron-green":        { name: "Cameron Green",         team: "KKR", role: "AR",   credit: 9.5 },
  "sunil-narine":         { name: "Sunil Narine",          team: "KKR", role: "AR",   credit: 10.0 },
  "rachin-ravindra":      { name: "Rachin Ravindra",       team: "KKR", role: "AR",   credit: 8.5 },
  "ramandeep-singh":      { name: "Ramandeep Singh",       team: "KKR", role: "AR",   credit: 7.5 },
  "anukul-roy":           { name: "Anukul Roy",            team: "KKR", role: "AR",   credit: 7.5 },
  "varun-chakravarthy":   { name: "Varun Chakravarthy",    team: "KKR", role: "BOWL", credit: 9.0 },
  "blessing-muzarabani":  { name: "Blessing Muzarabani",   team: "KKR", role: "BOWL", credit: 8.5 },
  "vaibhav-arora":        { name: "Vaibhav Arora",         team: "KKR", role: "BOWL", credit: 8.0 },
  "matheesha-pathirana":  { name: "Matheesha Pathirana",   team: "KKR", role: "BOWL", credit: 9.0 },
  "navdeep-saini":        { name: "Navdeep Saini",         team: "KKR", role: "BOWL", credit: 7.5 },
  "umran-malik":          { name: "Umran Malik",           team: "KKR", role: "BOWL", credit: 8.0 },

  // ─── LSG — Lucknow Super Giants ──────────────────────────────────────
  "rishabh-pant":         { name: "Rishabh Pant",          team: "LSG", role: "WK",   credit: 10.5 },
  "aiden-markram":        { name: "Aiden Markram",         team: "LSG", role: "AR",   credit: 9.0 },
  "himmat-singh":         { name: "Himmat Singh",          team: "LSG", role: "BAT",  credit: 7.5 },
  "matthew-breetzke":     { name: "Matthew Breetzke",      team: "LSG", role: "BAT",  credit: 7.5 },
  "josh-inglis":          { name: "Josh Inglis",           team: "LSG", role: "WK",   credit: 8.0 },
  "nicholas-pooran":      { name: "Nicholas Pooran",       team: "LSG", role: "WK",   credit: 9.5 },
  "mitchell-marsh":       { name: "Mitchell Marsh",        team: "LSG", role: "AR",   credit: 9.5 },
  "abdul-samad":          { name: "Abdul Samad",           team: "LSG", role: "AR",   credit: 8.0 },
  "shahbaz-ahmed":        { name: "Shahbaz Ahmed",         team: "LSG", role: "AR",   credit: 8.5 },
  "arshin-kulkarni":      { name: "Arshin Kulkarni",       team: "LSG", role: "AR",   credit: 7.5 },
  "wanindu-hasaranga":    { name: "Wanindu Hasaranga",     team: "LSG", role: "AR",   credit: 9.5 },
  "ayush-badoni":         { name: "Ayush Badoni",          team: "LSG", role: "AR",   credit: 8.0 },
  "mohammad-shami":       { name: "Mohammad Shami",        team: "LSG", role: "BOWL", credit: 10.0 },
  "avesh-khan":           { name: "Avesh Khan",            team: "LSG", role: "BOWL", credit: 8.5 },
  "mayank-yadav":         { name: "Mayank Yadav",          team: "LSG", role: "BOWL", credit: 8.5 },
  "anrich-nortje":        { name: "Anrich Nortje",         team: "LSG", role: "BOWL", credit: 9.0 },
  "digvesh-singh":        { name: "Digvesh Singh",         team: "LSG", role: "BOWL", credit: 7.0 },
  "arjun-tendulkar":      { name: "Arjun Tendulkar",       team: "LSG", role: "BOWL", credit: 7.0 },
  "mohsin-khan":          { name: "Mohsin Khan",           team: "LSG", role: "BOWL", credit: 8.0 },

  // ─── MI — Mumbai Indians ─────────────────────────────────────────────
  "rohit-sharma":         { name: "Rohit Sharma",          team: "MI",  role: "BAT",  credit: 10.5 },
  "suryakumar-yadav":     { name: "Suryakumar Yadav",      team: "MI",  role: "BAT",  credit: 10.0 },
  "ryan-rickelton":       { name: "Ryan Rickelton",        team: "MI",  role: "WK",   credit: 8.5 },
  "quinton-de-kock":      { name: "Quinton de Kock",       team: "MI",  role: "WK",   credit: 9.5 },
  "tilak-varma":          { name: "N. Tilak Varma",        team: "MI",  role: "BAT",  credit: 9.0 },
  "robin-minz":           { name: "Robin Minz",            team: "MI",  role: "WK",   credit: 7.5 },
  "sherfane-rutherford":  { name: "Sherfane Rutherford",   team: "MI",  role: "BAT",  credit: 8.0 },
  "hardik-pandya":        { name: "Hardik Pandya",         team: "MI",  role: "AR",   credit: 10.0 },
  "naman-dhir":           { name: "Naman Dhir",            team: "MI",  role: "AR",   credit: 8.0 },
  "mitchell-santner":     { name: "Mitchell Santner",      team: "MI",  role: "AR",   credit: 8.5 },
  "will-jacks":           { name: "Will Jacks",            team: "MI",  role: "AR",   credit: 8.5 },
  "shardul-thakur":       { name: "Shardul Thakur",        team: "MI",  role: "AR",   credit: 8.5 },
  "corbin-bosch":         { name: "Corbin Bosch",          team: "MI",  role: "AR",   credit: 7.5 },
  "jasprit-bumrah":       { name: "Jasprit Bumrah",        team: "MI",  role: "BOWL", credit: 11.0 },
  "trent-boult":          { name: "Trent Boult",           team: "MI",  role: "BOWL", credit: 9.0 },
  "deepak-chahar":        { name: "Deepak Chahar",         team: "MI",  role: "BOWL", credit: 8.5 },
  "allah-ghazanfar":      { name: "Allah Ghazanfar",       team: "MI",  role: "BOWL", credit: 8.0 },
  "mayank-markande":      { name: "Mayank Markande",       team: "MI",  role: "BOWL", credit: 7.5 },

  // ─── PBKS — Punjab Kings ─────────────────────────────────────────────
  "shreyas-iyer":         { name: "Shreyas Iyer",          team: "PBKS", role: "BAT", credit: 10.0 },
  "prabhsimran-singh":    { name: "Prabhsimran Singh",     team: "PBKS", role: "WK",  credit: 8.5 },
  "shashank-singh":       { name: "Shashank Singh",        team: "PBKS", role: "BAT", credit: 8.5 },
  "nehal-wadhera":        { name: "Nehal Wadhera",         team: "PBKS", role: "BAT", credit: 8.0 },
  "vishnu-vinod":         { name: "Vishnu Vinod",          team: "PBKS", role: "WK",  credit: 7.5 },
  "harnoor-pannu":        { name: "Harnoor Pannu",         team: "PBKS", role: "BAT", credit: 7.0 },
  "priyansh-arya":        { name: "Priyansh Arya",         team: "PBKS", role: "AR",  credit: 8.0 },
  "musheer-khan":         { name: "Musheer Khan",          team: "PBKS", role: "AR",  credit: 8.0 },
  "marcus-stoinis":       { name: "Marcus Stoinis",        team: "PBKS", role: "AR",  credit: 9.5 },
  "marco-jansen":         { name: "Marco Jansen",          team: "PBKS", role: "AR",  credit: 9.0 },
  "azmatullah-omarzai":   { name: "Azmatullah Omarzai",    team: "PBKS", role: "AR",  credit: 8.5 },
  "mitch-owen":           { name: "Mitch Owen",            team: "PBKS", role: "AR",  credit: 7.5 },
  "cooper-connolly":      { name: "Cooper Connolly",       team: "PBKS", role: "AR",  credit: 7.5 },
  "harpreet-brar":        { name: "Harpreet Brar",         team: "PBKS", role: "AR",  credit: 8.0 },
  "arshdeep-singh":       { name: "Arshdeep Singh",        team: "PBKS", role: "BOWL", credit: 9.5 },
  "yuzvendra-chahal":     { name: "Yuzvendra Chahal",      team: "PBKS", role: "BOWL", credit: 9.0 },
  "lockie-ferguson":      { name: "Lockie Ferguson",       team: "PBKS", role: "BOWL", credit: 8.5 },
  "vyshak-vijaykumar":    { name: "Vyshak Vijaykumar",     team: "PBKS", role: "BOWL", credit: 8.0 },
  "yash-thakur":          { name: "Yash Thakur",           team: "PBKS", role: "BOWL", credit: 8.0 },
  "xavier-bartlett":      { name: "Xavier Bartlett",       team: "PBKS", role: "BOWL", credit: 8.0 },
  "ben-dwarshuis":        { name: "Ben Dwarshuis",         team: "PBKS", role: "BOWL", credit: 7.5 },

  // ─── RR — Rajasthan Royals ───────────────────────────────────────────
  "yashasvi-jaiswal":     { name: "Yashasvi Jaiswal",      team: "RR",  role: "BAT",  credit: 10.5 },
  "riyan-parag":          { name: "Riyan Parag",           team: "RR",  role: "AR",   credit: 9.5 },
  "dhruv-jurel":          { name: "Dhruv Jurel",           team: "RR",  role: "WK",   credit: 8.5 },
  "shimron-hetmyer":      { name: "Shimron Hetmyer",       team: "RR",  role: "BAT",  credit: 9.0 },
  "vaibhav-suryavanshi":  { name: "Vaibhav Suryavanshi",   team: "RR",  role: "BAT",  credit: 8.0 },
  "shubham-dubey":        { name: "Shubham Dubey",         team: "RR",  role: "AR",   credit: 8.0 },
  "donovan-ferreira":     { name: "Donovan Ferreira",      team: "RR",  role: "BAT",  credit: 7.5 },
  "ravindra-jadeja":      { name: "Ravindra Jadeja",       team: "RR",  role: "AR",   credit: 10.0 },
  "dasun-shanaka":        { name: "Dasun Shanaka",         team: "RR",  role: "AR",   credit: 8.0 },
  "yudhvir-charak":       { name: "Yudhvir Singh Charak",  team: "RR",  role: "AR",   credit: 8.0 },
  "jofra-archer":         { name: "Jofra Archer",          team: "RR",  role: "BOWL", credit: 9.5 },
  "tushar-deshpande":     { name: "Tushar Deshpande",      team: "RR",  role: "BOWL", credit: 8.5 },
  "ravi-bishnoi":         { name: "Ravi Bishnoi",          team: "RR",  role: "BOWL", credit: 9.0 },
  "kwena-maphaka":        { name: "Kwena Maphaka",         team: "RR",  role: "BOWL", credit: 8.0 },
  "sandeep-sharma":       { name: "Sandeep Sharma",        team: "RR",  role: "BOWL", credit: 8.0 },
  "adam-milne":           { name: "Adam Milne",            team: "RR",  role: "BOWL", credit: 7.5 },
  "nandre-burger":        { name: "Nandre Burger",         team: "RR",  role: "BOWL", credit: 8.0 },

  // ─── RCB — Royal Challengers Bengaluru ───────────────────────────────
  "virat-kohli":          { name: "Virat Kohli",           team: "RCB", role: "BAT",  credit: 11.0 },
  "rajat-patidar":        { name: "Rajat Patidar",         team: "RCB", role: "BAT",  credit: 9.5 },
  "devdutt-padikkal":     { name: "Devdutt Padikkal",      team: "RCB", role: "BAT",  credit: 8.5 },
  "phil-salt":            { name: "Phil Salt",             team: "RCB", role: "WK",   credit: 9.0 },
  "jitesh-sharma":        { name: "Jitesh Sharma",         team: "RCB", role: "WK",   credit: 8.5 },
  "jordan-cox":           { name: "Jordan Cox",            team: "RCB", role: "WK",   credit: 7.5 },
  "krunal-pandya":        { name: "Krunal Pandya",         team: "RCB", role: "AR",   credit: 9.0 },
  "tim-david":            { name: "Tim David",             team: "RCB", role: "AR",   credit: 9.5 },
  "romario-shepherd":     { name: "Romario Shepherd",      team: "RCB", role: "AR",   credit: 8.5 },
  "jacob-bethell":        { name: "Jacob Bethell",         team: "RCB", role: "AR",   credit: 8.5 },
  "venkatesh-iyer":       { name: "Venkatesh Iyer",        team: "RCB", role: "AR",   credit: 9.0 },
  "swapnil-singh":        { name: "Swapnil Singh",         team: "RCB", role: "AR",   credit: 7.5 },
  "vicky-ostwal":         { name: "Vicky Ostwal",          team: "RCB", role: "BOWL", credit: 7.5 },
  "mangesh-yadav":        { name: "Mangesh Yadav",         team: "RCB", role: "BOWL", credit: 7.5 },
  "josh-hazlewood":       { name: "Josh Hazlewood",        team: "RCB", role: "BOWL", credit: 9.0 },
  "rasikh-dar":           { name: "Rasikh Dar",            team: "RCB", role: "BOWL", credit: 8.0 },
  "suyash-sharma":        { name: "Suyash Sharma",         team: "RCB", role: "BOWL", credit: 7.5 },
  "bhuvneshwar-kumar":    { name: "Bhuvneshwar Kumar",     team: "RCB", role: "BOWL", credit: 8.5 },
  "nuwan-thushara":       { name: "Nuwan Thushara",        team: "RCB", role: "BOWL", credit: 8.0 },
  "yash-dayal":           { name: "Yash Dayal",            team: "RCB", role: "BOWL", credit: 7.5 },

  // ─── SRH — Sunrisers Hyderabad ───────────────────────────────────────
  "ishan-kishan":         { name: "Ishan Kishan",          team: "SRH", role: "WK",   credit: 9.0 },
  "travis-head":          { name: "Travis Head",           team: "SRH", role: "BAT",  credit: 10.5 },
  "heinrich-klaasen":     { name: "Heinrich Klaasen",      team: "SRH", role: "WK",   credit: 10.0 },
  "aniket-verma":         { name: "Aniket Verma",          team: "SRH", role: "BAT",  credit: 7.5 },
  "smaran-ravichandran":  { name: "Smaran Ravichandran",   team: "SRH", role: "BAT",  credit: 7.0 },
  "abhishek-sharma":      { name: "Abhishek Sharma",       team: "SRH", role: "AR",   credit: 9.0 },
  "nitish-reddy":         { name: "Nitish Kumar Reddy",    team: "SRH", role: "AR",   credit: 9.0 },
  "harshal-patel":        { name: "Harshal Patel",         team: "SRH", role: "AR",   credit: 8.5 },
  "liam-livingstone":     { name: "Liam Livingstone",      team: "SRH", role: "AR",   credit: 9.0 },
  "kamindu-mendis":       { name: "Kamindu Mendis",        team: "SRH", role: "AR",   credit: 8.5 },
  "brydon-carse":         { name: "Brydon Carse",          team: "SRH", role: "AR",   credit: 8.5 },
  "pat-cummins":          { name: "Pat Cummins",           team: "SRH", role: "AR",   credit: 10.0 },
  "jaydev-unadkat":       { name: "Jaydev Unadkat",        team: "SRH", role: "BOWL", credit: 8.0 },
  "zeeshan-ansari":       { name: "Zeeshan Ansari",        team: "SRH", role: "BOWL", credit: 7.5 },
  "shivam-mavi":          { name: "Shivam Mavi",           team: "SRH", role: "BOWL", credit: 8.0 },
};

// ── Helper: get players for a specific team ───────────────────────────────
export const getTeamPlayers = (teamCode) =>
  Object.entries(PLAYERS)
    .filter(([, p]) => p.team === teamCode)
    .map(([id, p]) => ({ id, ...p }));

// ── Helper: get players for two teams (a match) ───────────────────────────
export const getMatchPlayers = (team1, team2) =>
  Object.entries(PLAYERS)
    .filter(([, p]) => p.team === team1 || p.team === team2)
    .map(([id, p]) => ({ id, ...p }));

// ── Name → ID lookup (for scorecard matching) ─────────────────────────────
export const NAME_TO_ID = Object.entries(PLAYERS).reduce((acc, [id, p]) => {
  acc[p.name.toLowerCase()] = id;
  return acc;
}, {});

export const TEAM_CODES = ["MI","CSK","RCB","KKR","DC","SRH","PBKS","RR","GT","LSG"];
